### ISSUE TITLE
Too big docker context can probably cause OOM 

### ISSUE THREAD

**Issue by jakubno** [e2b-dev/infra#51]
```
Preparing sandbox template building (38490 files in Docker build context). 
Found ./e2b.Dockerfile that will be used to build the sandbox template.
Error: Build API request failed: Service Unavailable
    at zX (/usr/local/npm/lib/node_modules/@e2b/cli/dist/index.js:151:912)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async e.<anonymous> (/usr/local/npm/lib/node_modules/@e2b/cli/dist/index.js:123:1425)
 ```

Fixing the order or middlewares + some other limit setup could maybe fix this.
![image](https://github.com/e2b-dev/infra/assets/50249709/8a5a932d-b210-4b93-b3e8-9919564446c1)

**Comment by jakubno** [comment]
Solved by da7f1ae
